drop table if exists flipp_oms.MARKETING_PROGRAM_LOCALIZED;
CREATE TABLE flipp_oms.MARKETING_PROGRAM (
	id BIGINT PRIMARY KEY

);


drop table if exists flipp_oms.MARKETING_PROGRAM_LOCALIZED;

CREATE TABLE flipp_oms.MARKETING_PROGRAM_LOCALIZED (
	marketing_program_id BIGINT,
	locale_id VARCHAR(2),
	name VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY(marketing_program_id, locale_id),
	FOREIGN KEY (marketing_program_id) REFERENCES flipp_oms.MARKETING_PROGRAM (id),
    FOREIGN KEY (locale_id) REFERENCES flipp_oms.LOCALE (code)
);

CREATE TABLE flipp_oms.LOCALE (
	code VARCHAR(2) PRIMARY KEY
);

SELECT * FROM flipp_oms.MARKETING_PROGRAM;
SELECT * FROM flipp_oms.MARKETING_PROGRAM_LOCALIZED;

INSERT INTO flipp_oms.LOCALE VALUES('en');
INSERT INTO flipp_oms.LOCALE VALUES('ru');

INSERT INTO flipp_oms.MARKETING_PROGRAM VALUES(1);
INSERT INTO flipp_oms.MARKETING_PROGRAM VALUES(2);

INSERT INTO flipp_oms.MARKETING_PROGRAM_LOCALIZED VALUES(1, 'en', 'U.K.');
INSERT INTO flipp_oms.MARKETING_PROGRAM_LOCALIZED VALUES(1, 'ru', 'USA');
INSERT INTO flipp_oms.MARKETING_PROGRAM_LOCALIZED VALUES(2, 'ru', 'USA');

